version: '3'

services:
  redis:
    image: redis:6.2.6
    container_name: "siribot-cache"
    command: bash -c "redis-server --appendonly yes"
    restart: always
    expose:
      - 6379
    volumes:
      - ./cache:/data

  prometheus:
    image: prom/prometheus:v2.29.2
    container_name: prometheus
    restart: always
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --storage.tsdb.retention=1y
    expose:
      - 9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:8.3.3
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_REGION: ${AWS_DEFAULT_REGION}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  siribot:
    container_name: "siribot"
    image: bbergerdocker/discord-kitt:1.0.13
    restart: unless-stopped
    depends_on:
      - redis
    expose:
      - 3001
    volumes:
      - ./settings:/usr/src/app/settings
    env_file:
      - .env

volumes:
  prometheus_data:
  grafana_data:
