version: '3'

services:
  redis:
    image: redis:latest
    container_name: "siribot-cache"
    command: bash -c "redis-server --appendonly yes"
    expose:
      - 6379
    volumes:
      - ./cache:/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --storage.tsdb.retention=1y
    expose:
      - 9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/config.ini:/etc/grafana/config.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  siribot:
    container_name: "siribot"
    image: smartdockerrepo.azurecr.io/deca/siribot:latest
    restart: unless-stopped
    command: node dist/index.js
    depends_on:
      - redis
    expose:
      - 3001
    volumes:
      - ./settings:/usr/src/app/settings
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      OWNER_ID: ${OWNER_ID}
      BOT_ID: ${BOT_ID}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      REDIS_URL: ${REDIS_URL}
      TOP_GG: ${TOP_GG}
      DISCORD_BOTS_GG: ${DISCORD_BOTS_GG}
      DISCORD_BOT_LIST: ${DISCORD_BOT_LIST}
      NODE_ENV: production

volumes:
  prometheus_data:
  grafana_data:
