{
 "title": "Siri Bot",
 "description": "Siri Bot stats",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nodejs_version_info, instance)"
    }
   },
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(nodejs_active_handles, group)"
    }
   },
   {
    "name": "stack",
    "label": "Stack",
    "query": {
     "query": "label_values(nodejs_active_handles{group=\"$group\"},stack)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(nodejs_active_handles,service)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(nodejs_active_handles{stack=\"$stack\",service=\"$service\"},host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Application Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$service Process start time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(process_start_time_seconds{service=~\"$service\", stack=~\"$stack\"})*1000",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "% of Guilds Using",
   "type": "stat",
   "description": "% of guilds where the bot is in an active voice channel",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "(voice_total/guild_total)" }
   ]
  },
  {
   "title": "Guilds",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "guild_total" }
   ]
  },
  {
   "title": "Voice Channels",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "voice_total" }
   ]
  },
  {
   "title": "Announcements Made",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "announcement_phrase_total" }
   ]
  },
  {
   "title": "Leave Phrases Added",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "leave_phrase_total" }
   ]
  },
  {
   "title": "$service Nodejs Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nodejs_version_info{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "$service Process Heap",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_heap_bytes{stack=~\"$stack\",service=~\"$service\"}"
    }
   ]
  },
  {
   "title": "Join Phrases Added",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "join_phrase_total" }
   ]
  },
  {
   "title": "$service Metrics scrape duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{stack=~\"$stack\",service=~\"$service\", host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Command Totals",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "targets": [
    { "expr": "help_command_total", "legendFormat": "help" },
    { "expr": "prefix_command_total", "legendFormat": "prefix" },
    { "expr": "ping_command_total", "legendFormat": "ping" },
    { "expr": "eval_command_total", "legendFormat": "eval" },
    { "expr": "groups_command_total", "legendFormat": "groups" },
    { "expr": "enable_command_total", "legendFormat": "enable" },
    { "expr": "reload_command_total", "legendFormat": "reload" },
    { "expr": "load_command_total", "legendFormat": "load" },
    { "expr": "unload_command_total", "legendFormat": "unload" },
    { "expr": "default_command_total", "legendFormat": "default" },
    { "expr": "disable_event_command_total", "legendFormat": "disable" },
    { "expr": "enable_event_command_total", "legendFormat": "enable" },
    { "expr": "events_command_total", "legendFormat": "events" },
    { "expr": "join_command_total", "legendFormat": "join" },
    { "expr": "leave_command_total", "legendFormat": "leave" },
    { "expr": "list_command_total", "legendFormat": "list" },
    { "expr": "phrase_command_total", "legendFormat": "phrase" },
    { "expr": "rejoin_command_total", "legendFormat": "rejoin" },
    { "expr": "reset_command_total", "legendFormat": "reset" },
    { "expr": "say_auto_delete_command_total", "legendFormat": "say auto delete" },
    { "expr": "say_command_total", "legendFormat": "say" },
    { "expr": "speed_command_total", "legendFormat": "speed" },
    { "expr": "test_command_total", "legendFormat": "test" },
    { "expr": "voice_command_total", "legendFormat": "voice" },
    { "expr": "voices_command_total", "legendFormat": "voices" },
    { "expr": "flip_command_total", "legendFormat": "flip" },
    { "expr": "leave_guild_command_total", "legendFormat": "leave guild" },
    { "expr": "restart_command_total", "legendFormat": "restart" },
    { "expr": "updatebotlists_command_total", "legendFormat": "update bot lists" },
    { "expr": "uptime_command_total", "legendFormat": "uptime" }
   ]
  },
  { "title": "CPU & Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{instance=~\"$instance\"}[2m]) * 100",
     "legendFormat": "User CPU - {{instance}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{instance=~\"$instance\"}[2m]) * 100",
     "legendFormat": "Sys CPU - {{instance}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "Process Memory - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Total - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  { "title": "Heap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Heap Total Detail",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Total - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  }
 ]
}